defaults:
  - baseline

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}_FT_BOMEX50_Train=BOMEX50_v2_mode_train_lr5.0e-05train_lora/${now:%H-%M-%S}
#    dir: ../outputs/${now:%Y-%m-%d}_tmp/${now:%H-%M-%S}

resume: True
stats_print_interval: 5
validation_iter_interval: 5
checkpoint_iteration_interval: 5
#checkpoint_resume_path: '/wdata/roironen/Deploy/ProbCT/outputs/2023-04-05_BOMEX_500CCN_10cameras_20m_V1_noise/14-16-49/checkpoints/cp_230000.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/ProbCT/outputs/2023-04-05_BOMEX_50CCN_10cameras_20m_V1_noise/14-15-58/checkpoints/cp_225000.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/ProbCT/outputs/2022-03-31_BOMEX_Res50_FPN_512channels_Sampl_3_9_10cams_L2_relative_LR5.0e-05_FixCTv4_wd1.0e-05_n_sampling_nets10/00-36-48/checkpoints/cp_130000.pth'
checkpoint_resume_path: '/wdata/roironen/Deploy/ProbCT/outputs/2023-07-16_FT_BOMEX50_Train=BOMEX50_v2_mode_train_lr5.0e-05train_lora/18-12-46/checkpoints/cp_60.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/ProbCT/outputs/2023-04-06_FT_BOMEX_50CCN_10cameras_20m_V2_LR5.0e-06/20-25-06/checkpoints/cp_1100.pth'
#checkpoint_resume_path: '/wdata/roironen/Deploy/ProbCT/outputs/2023-04-05_BOMEX_500CCN_10cameras_20m_CE_noise/14-14-03/checkpoints/cp_230000.pth'
gpu: 0

data:
  dataset_name: 'BOMEX_50CCN_10cameras_20m' #'HAWAII_2000CCN_10cameras_20m' BOMEX_10cameras_20m#'BOMEX_50CCN_10cameras_20m' #'CASS_600CCN_roiprocess_10cameras_20m'
  n_training: -1
  n_val: 50
  noise: True


optimizer:
  lr: 1.0e-05
  wd: 1.0e-05
  ce_weight_zero: False
  loss: 'L2'
  loss_thr: 3

cross_entropy:
  min: 0
  max: 300
  bins: 301

ct_net:
  pred_type: 'differentiable_max'
  prob_gain: 10
  conf_type: 'entropy' #conf_interval prob std rel_prob
  decoder_batchify: True
  stop_encoder_grad: True
  encoder_mode: 'train'


decoder:
  name: 'FixCTv4_CE' #'CE' #FixCTv4_CE FixCTv4_CE_mask
  apply_lora: False
  lora_dim: 64
  lora_alpha: 1000
  lora_dropout: 0
  fan_in_fan_out: False
  merge_weights: False

shdom:
  n_jobs: 40
  n_clouds: 1
  use_forward_grid: True
  add_rayleigh: True
  use_forward_phase_albedo: False
