hydra:
  run:
    dir: ../test_results/${now:%Y-%m-%d}_Exp1/${now:%H-%M-%S}
seed: 3
debug: False
gpu: 0
save_results: False
show: False
mode: train

checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-19_FT_BOMEX500_Train_BOMEX500_v2/10-10-37/checkpoints/cp_500.pth'

data:
  dataset_name: 'BOMEX_5000CCN_new_10cameras_20m'
#  dataset_name: 'Toy2_10cameras_20m'
#  dataset_name: 'Toy3_10cameras_20m'
#  dataset_name: 'CASS_600CCN_roiprocess_10cameras_20m'
#  dataset_name: 'HAWAII_2000CCN_10cameras_20m'
#  dataset_name: 'DYCOMS_RF02_500CCN_10cameras_20m'
#  dataset_name: 'DYCOMS_RF02_50CCN_10cameras_20m'
#  dataset_name: 'BOMEX_50CCN_10cameras_20m'
  n_val: -1
  image_size: 116

ct_net:
  val_n_query: 100
  val_mask_type: 'space_carving' # 'space_carving' 'gt_mask' None toy3
  pred_type: 'max' #max
  conf_type: 'entropy' #conf_interval prob std rel_prob
  decoder_batchify: True

min_mask_points: 0
decoder:
  type: 'mlp' #mlp transformer

version:
  'V2'